# Browser to use: chrome | firefox | edge
browser=chrome

# Base URL
baseUrl=https://www.coursera.org

# Implicit wait (seconds)
implicitWait=10

# Explicit wait (seconds)
explicitWait=15

# Page load timeout (seconds)
maxWaitTime=30

# Number of courses to extract
#coursesToExtract=10

# Excel output file path
excelOutputPath=src/test/resources/testdata/CourseData.xlsx